services:
  db:
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    volumes:
      - redis_data:/data

  app:
    image: ${DOCKER_IMAGE:-ghcr.io/kyumin1227/gsc-slack-app:dev}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app

volumes:
  redis_data:
